name: yura_trophy
description: An app to track your progress as a PSN trophy hunter.

publish_to: 'none'

version: 0.4.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  country_icons: ^1.1.1
  cupertino_icons: ^1.0.2
  flutter_easyloading: ^2.2.2
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  intl: ^0.16.1
  url_launcher: ^5.7.10
  web_scraper: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
